version: "3.2"
services:
  php:
    build: 
      context: './php'
    ports:
      - "9001:80"
    depends_on:
      - tpac_db 
    networks:
      - frontend
      - backend
    volumes:
      - ./api/:/var/www/html/
    container_name: tpac_api

  tpac_admin:
    build:
      context: './admin/'
    networks:
      - frontend
    ports:
      - "9002:8080"
    container_name: tpac_admin

  tpac_db:
    image: mysql:${MYSQL_VERSION:-latest}
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    container_name: tpac_db 
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./db:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    networks:
      - backend
    ports:
      - 9080:80
    environment:
      - PMA_ARBITRARY=1



networks:
  frontend:
  backend:
volumes:
  dbdata:
